### ISSUE TITLE
How to Run on Android Phone or Android TV or Kodi?

### ISSUE THREAD

**Issue by jaypatel16** [alluringabhi/iptv1#1]
Thank you so much for list.

But I am not getting how to run this on android TV or phone?

Can I add this as Kodi Addon?

Please suggest, how you run this IPTV channels?

**Comment by alluringabhi** [comment]
Use list in perfect player

**Comment by jaypatel16** [comment]
Thanks all airtel channels are working fine. 
Should I have to configure anything for JIO TV channels?

**Comment by jaypatel16** [comment]
I am able to generate Jio Token from using script created by https://github.com/allscriptz/jiotv and set User Agent in Perfect player as  "AppleWebKit/JioTV/537.36", still its not working in Perfect player

**Comment by alluringabhi** [comment]
Bro just paste this link in perfect player and set decoder to hw+ in
setting things will work fine, also explain how to use scripts to me i am
new in using scripts.

**Comment by alluringabhi** [comment]
https://raw.githubusercontent.com/alluringabhi/iptv1/master/airtel.m3u
paste this in perfect player also share more channels.

**Comment by jaypatel16** [comment]
Run this file https://raw.githubusercontent.com/allscriptz/jiotv/master/jioToken.php

in below editor, you get refreshed token
https://paiza.io/projects/fDDOU4a-zeM5kNc_2C5IFQ

**Comment by jaypatel16** [comment]
by doing HW+, i am able to play all channels. Thanks man.

**Comment by alluringabhi** [comment]
no problem bro, do you have any other scripts like for d2h dish tv an tata
sky, also send whatever you have.
